### ISSUE TITLE
GNOME 45 support

### ISSUE THREAD

**Issue by sempasha** [alexispurslane/PRIME-GPU-Profile-Selector#5]
Extension is not compatible with GNOME 45 for now.

**Comment by alexispurslane** [comment]
Apologies. I nominally translated the code a few days after gnome 45 came out, just directly translating all of the syntax and fixing the basic bugs, but there's some deeper bug that I didn't have the time to fix at the time, and I've since been really struggling with my disability. If anyone wants to make a fix I'd be happy to merge it. And maybe I'll feel up to pushing the partially ported code on a branch in a few days.

**Comment by alexispurslane** [comment]
@sempasha okay, it's updated. The icons aren't working yet, but everything else is.

Edit: icons are now working, and the design has been updated a bit to look more official as well.

**Comment by junocomp** [comment]
When are you pushing this to https://extensions.gnome.org?

**Comment by alexispurslane** [comment]
> When are you pushing this to https://extensions.gnome.org?

Apologies for the delay. I submitted this version the day I finished it, but I just got a review back from the extension store a few minutes ago. Apparently, the method I'm using to get access to the extension object for this extension is actually "bad practice," and instead I should be threading a reference to the extension via `this` through like three different intervening classes and methods that don't even need it just to get it to the one method that does, like a plumber. (They call that "dependency injection", but it absolutely isn't, ROFL), so I'm going to have to fix that before I can get it up on their extensions store, but right now I'm sick.
